name: Java CI/CD

on:
  push:
    branches:
      - main   # Run when code is pushed to the main branch
  pull_request:
    branches:
      - main   # Also run for pull requests to main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from your repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java environment
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'   # Popular open-source JDK

      # Step 3: Compile Java code
      - name: Compile Java files
        run: javac src/main/java/org/example/Sum.java

      # Step 4: Run the compiled program
      - name: Run Java program
        run: java -cp src/main/java org.example.Sum